version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    image: next-image
    container_name: next-container

    ports:
      - "3000:3000"

    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

    depends_on:
      - db

  db:
    image: postgres:latest

    # used to create the database credentials
    environment:
      POSTGRES_USER: ct3t-admin
      POSTGRES_PASSWORD: ct3t-pass
      POSTGRES_DB: ct3t-db

    ports:
      - "5432:5432"
